name: oss

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: A WEB JOB（OSS）
    steps:
    - name: Checout(获取源码)
      uses: actions/checkout@v1
    - name: Setup node(安装node环境)
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Cache node modules(缓存)
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{runner.OS}}-npm-caches-${{ hashFiles('pachage-lock.json') }} # Linux-npm-caches-e87d4692eafbc98fd7477e38aa502a6b39f20ffda3ab5bad51171838ca791f3c
    - name: Install Dep(安装依赖)
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - name: Build pro(编译)
      run: |
        npm run build:prod
    - name: Upload aliyun oss(上传项目到腾讯云服务器)
      env:
        HOST: 129.204.61.249
        USER: root
      run: |
	      sshpass -p ${{ secrets.ACTIONS_DEPLOY_KEY }} ssh  -o StrictHostKeyChecking=no  $USER@$HOST  << EOF
        cd /usr/local/web/blog/
	      rm -rf static/ index.html
        cp dist ./
        exit
        EOF

